name: Tests
on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        make
        make examples

    - name: Unit tests
      run: |
        sudo apt-get install -y gcovr lcov
        make libcheck
        make test

    - name: Upload the coverage
      if: github.ref == 'refs/heads/master'
      uses: codecov/codecov-action@v1

  OSX:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        make
        make examples

  Documentation:
    runs-on: ubuntu-18.04
    needs: Linux
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: actions/checkout@v2
        with:
          repository: niess/turtle-docs
          path: docs
          persist-credentials: false
          fetch-depth: 0

      - name: Install docurium
        run: |
          sudo apt update
          sudo apt install -y python-pygments libclang-8-dev llvm-8 clang-8
          sudo gem install docurium
      - uses: actions/checkout@v2
        with:
          repository: niess/docurium
          ref: 'new-style'
          path: docs/docurium

      - name: Build the docs
        run: |
          cd docs
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          cd ..
          LLVM_CONFIG=llvm-config-8 ./docs/update.sh
          cd docs
          git checkout HEAD~1 -- docs/index.html docs/js/docurium.js
          git commit -a --amend --no-edit
          cd ..

      - name: Push the docs
        uses: ad-m/github-push-action@master
        with:
          directory: docs
          repository: niess/turtle-docs
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          force: true

